// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLd1pMppvr4xDo2t7mA2cuF2WahXvAcPM',
    appId: '1:307356414647:web:636272e879414117f99332',
    messagingSenderId: '307356414647',
    projectId: 'e-book-store-e8858',
    authDomain: 'e-book-store-e8858.firebaseapp.com',
    storageBucket: 'e-book-store-e8858.appspot.com',
    measurementId: 'G-QKLNSXPCB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKPYmKk4QYMV0LBYWBx4LRrsZm4_dn1D8',
    appId: '1:307356414647:android:1a294b2b50fccb23f99332',
    messagingSenderId: '307356414647',
    projectId: 'e-book-store-e8858',
    storageBucket: 'e-book-store-e8858.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzGgkN_y59Ed0vO-7z7NKsYy9h-U7gtvg',
    appId: '1:307356414647:ios:02428e5ffa8ff679f99332',
    messagingSenderId: '307356414647',
    projectId: 'e-book-store-e8858',
    storageBucket: 'e-book-store-e8858.appspot.com',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzGgkN_y59Ed0vO-7z7NKsYy9h-U7gtvg',
    appId: '1:307356414647:ios:e83db2c9734ad0bef99332',
    messagingSenderId: '307356414647',
    projectId: 'e-book-store-e8858',
    storageBucket: 'e-book-store-e8858.appspot.com',
    iosBundleId: 'com.example.bookstore.RunnerTests',
  );
}
